/** tema: Light */
ThemeRegistry.register({
    id:   'light',
    name: 'Light',
    icon: '☀️',
    variables: {
        '--gold':                   '#b8860b',
        '--gold-light':             '#daa520',
        '--gold-dim':               'rgba(184,134,11,0.1)',
        '--bg':                     '#f5f5f0',
        '--bg2':                    '#ffffff',
        '--bg3':                    '#fafaf5',
        '--border':                 '#ddd8cc',
        '--text':                   '#2c2b26',
        '--muted':                  '#6b6a66',
        '--input-bg':               '#f0ede6',
        '--input-border':           '#ccc8bc',
        '--input-color':            '#2c2b26',
        '--row-even':               '#f9f7f2',
        '--td-border':              '#e8e4db',
        '--pill-bg':                '#f0ede6',
        '--palet-row-bg':           '#f5f3ee',
        '--flow-step-bg':           '#f0ede6',
        '--signin-input-bg':        '#f5f3ee',
        '--signin-input-border':    '#ccc8bc',
        '--header-bg':              'linear-gradient(180deg, #ffffff 0%, #f8f6f0 100%)',
        '--header-border':          'rgba(184,134,11,0.2)',
        '--sidebar-hover-color':    '#4a4840',
        '--shadow':                 '0 4px 24px rgba(0,0,0,0.1)',
        '--glass-blur':             '0px',
        '--glass-saturate':         '100%',
    },
    body: { bg: '', attachment: '' }
});
