/** tema: Gold Dark — default KMSU */
ThemeRegistry.register({
    id:   'gold',
    name: 'Gold Dark',
    icon: '🌟',
    variables: {
        '--gold':                   '#d4a017',
        '--gold-light':             '#e8c84a',
        '--gold-dim':               'rgba(212,160,23,0.18)',
        '--bg':                     '#0d0d0d',
        '--bg2':                    '#17140e',
        '--bg3':                    '#141210',
        '--border':                 '#2e2b20',
        '--text':                   '#e6dfd0',
        '--muted':                  '#8a8578',
        '--input-bg':               '#1a1a1a',
        '--input-border':           '#333',
        '--input-color':            '#e0d8c8',
        '--row-even':               '#11110e',
        '--td-border':              '#1f1f18',
        '--pill-bg':                '#111',
        '--palet-row-bg':           '#11110e',
        '--flow-step-bg':           '#111',
        '--signin-input-bg':        '#111',
        '--signin-input-border':    '#2a2720',
        '--header-bg':              'linear-gradient(180deg, #1a1610 0%, #14120c 100%)',
        '--header-border':          'rgba(212,160,23,0.3)',
        '--sidebar-hover-color':    '#c4b890',
        '--shadow':                 '0 4px 24px rgba(0,0,0,0.6)',
        '--glass-blur':             '0px',
        '--glass-saturate':         '100%',
    },
    body: { bg: '', attachment: '' }
});
