/** tema: Blue Steel */
ThemeRegistry.register({
    id:   'blue',
    name: 'Blue Steel',
    icon: '🔵',
    variables: {
        '--gold':                   '#3b82f6',
        '--gold-light':             '#60a5fa',
        '--gold-dim':               'rgba(59,130,246,0.15)',
        '--bg':                     '#0f172a',
        '--bg2':                    '#1e293b',
        '--bg3':                    '#334155',
        '--border':                 '#475569',
        '--text':                   '#e2e8f0',
        '--muted':                  '#94a3b8',
        '--input-bg':               '#1e293b',
        '--input-border':           '#475569',
        '--input-color':            '#e2e8f0',
        '--row-even':               '#0f172a',
        '--td-border':              '#334155',
        '--pill-bg':                '#0f172a',
        '--palet-row-bg':           '#1e293b',
        '--flow-step-bg':           '#0f172a',
        '--signin-input-bg':        '#0f172a',
        '--signin-input-border':    '#334155',
        '--header-bg':              'linear-gradient(180deg, #1e293b 0%, #0f172a 100%)',
        '--header-border':          'rgba(59,130,246,0.3)',
        '--sidebar-hover-color':    '#cbd5e1',
        '--shadow':                 '0 4px 24px rgba(0,0,0,0.6)',
        '--glass-blur':             '0px',
        '--glass-saturate':         '100%',
    },
    body: { bg: '', attachment: '' }
});
