/** tema: Forest */
ThemeRegistry.register({
    id:   'green',
    name: 'Forest',
    icon: '🌲',
    variables: {
        '--gold':                   '#2e7d32',
        '--gold-light':             '#4caf50',
        '--gold-dim':               'rgba(46,125,50,0.15)',
        '--bg':                     '#0a1f0a',
        '--bg2':                    '#0e2b0e',
        '--bg3':                    '#1a3b1a',
        '--border':                 '#2d5a2d',
        '--text':                   '#dcedc8',
        '--muted':                  '#9ecc9e',
        '--input-bg':               '#0e2b0e',
        '--input-border':           '#2d5a2d',
        '--input-color':            '#dcedc8',
        '--row-even':               '#0a1f0a',
        '--td-border':              '#1a3b1a',
        '--pill-bg':                '#0a1f0a',
        '--palet-row-bg':           '#0e2b0e',
        '--flow-step-bg':           '#0a1f0a',
        '--signin-input-bg':        '#0a1f0a',
        '--signin-input-border':    '#1a3b1a',
        '--header-bg':              'linear-gradient(180deg, #0e2b0e 0%, #0a1f0a 100%)',
        '--header-border':          'rgba(46,125,50,0.3)',
        '--sidebar-hover-color':    '#c8e6c9',
        '--shadow':                 '0 4px 24px rgba(0,0,0,0.6)',
        '--glass-blur':             '0px',
        '--glass-saturate':         '100%',
    },
    body: { bg: '', attachment: '' }
});
